# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.3"
manifest_format = "2.0"
project_hash = "74d68b51c0a6d6de22d75d5bb11e2a2839aba6b7"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[[deps.HashCode2014]]
deps = ["Artifacts"]
git-tree-sha1 = "fe59e0522d3d0cf83d3f1e44cc0832119b24f25f"
repo-rev = "no-python"
repo-url = "https://github.com/gdalle/HashCode2014.jl"
uuid = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"
version = "0.1.0"
