name = "JuliaOptimizationChallenge"
uuid = "9ba1bbbe-3db7-4b37-b4f9-ee5e44b79e74"
authors = ["yanwu-728 <74961465+yanwu-728@users.noreply.github.com>, danvil <69361955+DVILL17@users.noreply.github.com>, qhzhang"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
HashCode2014 = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"

[compat]
julia = "1.8"
BenchmarkTools = "1.3.2"
HashCode2014 = "0.1.0"
JuliaFormater = "1.0.15"
Aqua = "0.5.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
